DROP TABLE IF EXISTS `hotel_brand`;
CREATE TABLE IF NOT EXISTS `hotel_brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hotel_brand_name` VARCHAR(64) NOT NULL COMMENT '酒店品牌名称',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COMMENT = '酒店门店表';
