DROP TABLE IF EXISTS `product`;
CREATE TABLE IF NOT EXISTS `product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(32) NOT NULL COMMENT '单品编号',
  `productName` VARCHAR(64) NOT NULL COMMENT '单品名称',
  `mnemonicCode` VARCHAR(32) NOT NULL COMMENT '助记码',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COMMENT = '单品表';
